/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Direction {
  
  @SerializedName("routeIdxTo")
  private Integer routeIdxTo = null;
  @SerializedName("$")
  private String value = null;
  @SerializedName("routeIdxFrom")
  private Integer routeIdxFrom = null;

  /**
   * End of validity on total route
   **/
  @ApiModelProperty(required = true, value = "End of validity on total route")
  public Integer getRouteIdxTo() {
    return routeIdxTo;
  }
  public void setRouteIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getValue() {
    return value;
  }
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Start of validity on total route
   **/
  @ApiModelProperty(required = true, value = "Start of validity on total route")
  public Integer getRouteIdxFrom() {
    return routeIdxFrom;
  }
  public void setRouteIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Direction direction = (Direction) o;
    return (this.routeIdxTo == null ? direction.routeIdxTo == null : this.routeIdxTo.equals(direction.routeIdxTo)) &&
        (this.value == null ? direction.value == null : this.value.equals(direction.value)) &&
        (this.routeIdxFrom == null ? direction.routeIdxFrom == null : this.routeIdxFrom.equals(direction.routeIdxFrom));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.routeIdxTo == null ? 0: this.routeIdxTo.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    result = 31 * result + (this.routeIdxFrom == null ? 0: this.routeIdxFrom.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Direction {\n");
    
    sb.append("  routeIdxTo: ").append(routeIdxTo).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("  routeIdxFrom: ").append(routeIdxFrom).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
