/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class JourneyId {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("routeIdxTo")
  private Integer routeIdxTo = null;
  @SerializedName("routeIdxFrom")
  private Integer routeIdxFrom = null;

  /**
   * ID of this journey
   **/
  @ApiModelProperty(required = true, value = "ID of this journey")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * End of validity on total route
   **/
  @ApiModelProperty(required = true, value = "End of validity on total route")
  public Integer getRouteIdxTo() {
    return routeIdxTo;
  }
  public void setRouteIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
  }

  /**
   * Start of validity on total route
   **/
  @ApiModelProperty(required = true, value = "Start of validity on total route")
  public Integer getRouteIdxFrom() {
    return routeIdxFrom;
  }
  public void setRouteIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyId journeyId = (JourneyId) o;
    return (this.id == null ? journeyId.id == null : this.id.equals(journeyId.id)) &&
        (this.routeIdxTo == null ? journeyId.routeIdxTo == null : this.routeIdxTo.equals(journeyId.routeIdxTo)) &&
        (this.routeIdxFrom == null ? journeyId.routeIdxFrom == null : this.routeIdxFrom.equals(journeyId.routeIdxFrom));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.routeIdxTo == null ? 0: this.routeIdxTo.hashCode());
    result = 31 * result + (this.routeIdxFrom == null ? 0: this.routeIdxFrom.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyId {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  routeIdxTo: ").append(routeIdxTo).append("\n");
    sb.append("  routeIdxFrom: ").append(routeIdxFrom).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
