/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Color;
import io.swagger.client.model.Direction;
import io.swagger.client.model.GeometryRef;
import io.swagger.client.model.JourneyId;
import io.swagger.client.model.JourneyName;
import io.swagger.client.model.JourneyType;
import io.swagger.client.model.Stop;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class JourneyDetail {
  
  @SerializedName("JourneyType")
  private JourneyType journeyType = null;
  @SerializedName("errorText")
  private String errorText = null;
  @SerializedName("error")
  private String error = null;
  @SerializedName("serverdate")
  private Date serverdate = null;
  @SerializedName("servertime")
  private String servertime = null;
  @SerializedName("JourneyId")
  private JourneyId journeyId = null;
  @SerializedName("Direction")
  private Direction direction = null;
  @SerializedName("Stop")
  private List<Stop> stop = null;
  @SerializedName("JourneyName")
  private JourneyName journeyName = null;
  @SerializedName("GeometryRef")
  private GeometryRef geometryRef = null;
  @SerializedName("Color")
  private Color color = null;
  @SerializedName("noNamespaceSchemaLocation")
  private String noNamespaceSchemaLocation = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public JourneyType getJourneyType() {
    return journeyType;
  }
  public void setJourneyType(JourneyType journeyType) {
    this.journeyType = journeyType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getErrorText() {
    return errorText;
  }
  public void setErrorText(String errorText) {
    this.errorText = errorText;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }
  public void setError(String error) {
    this.error = error;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getServerdate() {
    return serverdate;
  }
  public void setServerdate(Date serverdate) {
    this.serverdate = serverdate;
  }

  /**
   * Current server time in format HH:MM
   **/
  @ApiModelProperty(value = "Current server time in format HH:MM")
  public String getServertime() {
    return servertime;
  }
  public void setServertime(String servertime) {
    this.servertime = servertime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public JourneyId getJourneyId() {
    return journeyId;
  }
  public void setJourneyId(JourneyId journeyId) {
    this.journeyId = journeyId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Direction getDirection() {
    return direction;
  }
  public void setDirection(Direction direction) {
    this.direction = direction;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Stop> getStop() {
    return stop;
  }
  public void setStop(List<Stop> stop) {
    this.stop = stop;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public JourneyName getJourneyName() {
    return journeyName;
  }
  public void setJourneyName(JourneyName journeyName) {
    this.journeyName = journeyName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public GeometryRef getGeometryRef() {
    return geometryRef;
  }
  public void setGeometryRef(GeometryRef geometryRef) {
    this.geometryRef = geometryRef;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Color getColor() {
    return color;
  }
  public void setColor(Color color) {
    this.color = color;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getNoNamespaceSchemaLocation() {
    return noNamespaceSchemaLocation;
  }
  public void setNoNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyDetail journeyDetail = (JourneyDetail) o;
    return (this.journeyType == null ? journeyDetail.journeyType == null : this.journeyType.equals(journeyDetail.journeyType)) &&
        (this.errorText == null ? journeyDetail.errorText == null : this.errorText.equals(journeyDetail.errorText)) &&
        (this.error == null ? journeyDetail.error == null : this.error.equals(journeyDetail.error)) &&
        (this.serverdate == null ? journeyDetail.serverdate == null : this.serverdate.equals(journeyDetail.serverdate)) &&
        (this.servertime == null ? journeyDetail.servertime == null : this.servertime.equals(journeyDetail.servertime)) &&
        (this.journeyId == null ? journeyDetail.journeyId == null : this.journeyId.equals(journeyDetail.journeyId)) &&
        (this.direction == null ? journeyDetail.direction == null : this.direction.equals(journeyDetail.direction)) &&
        (this.stop == null ? journeyDetail.stop == null : this.stop.equals(journeyDetail.stop)) &&
        (this.journeyName == null ? journeyDetail.journeyName == null : this.journeyName.equals(journeyDetail.journeyName)) &&
        (this.geometryRef == null ? journeyDetail.geometryRef == null : this.geometryRef.equals(journeyDetail.geometryRef)) &&
        (this.color == null ? journeyDetail.color == null : this.color.equals(journeyDetail.color)) &&
        (this.noNamespaceSchemaLocation == null ? journeyDetail.noNamespaceSchemaLocation == null : this.noNamespaceSchemaLocation.equals(journeyDetail.noNamespaceSchemaLocation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.journeyType == null ? 0: this.journeyType.hashCode());
    result = 31 * result + (this.errorText == null ? 0: this.errorText.hashCode());
    result = 31 * result + (this.error == null ? 0: this.error.hashCode());
    result = 31 * result + (this.serverdate == null ? 0: this.serverdate.hashCode());
    result = 31 * result + (this.servertime == null ? 0: this.servertime.hashCode());
    result = 31 * result + (this.journeyId == null ? 0: this.journeyId.hashCode());
    result = 31 * result + (this.direction == null ? 0: this.direction.hashCode());
    result = 31 * result + (this.stop == null ? 0: this.stop.hashCode());
    result = 31 * result + (this.journeyName == null ? 0: this.journeyName.hashCode());
    result = 31 * result + (this.geometryRef == null ? 0: this.geometryRef.hashCode());
    result = 31 * result + (this.color == null ? 0: this.color.hashCode());
    result = 31 * result + (this.noNamespaceSchemaLocation == null ? 0: this.noNamespaceSchemaLocation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyDetail {\n");
    
    sb.append("  journeyType: ").append(journeyType).append("\n");
    sb.append("  errorText: ").append(errorText).append("\n");
    sb.append("  error: ").append(error).append("\n");
    sb.append("  serverdate: ").append(serverdate).append("\n");
    sb.append("  servertime: ").append(servertime).append("\n");
    sb.append("  journeyId: ").append(journeyId).append("\n");
    sb.append("  direction: ").append(direction).append("\n");
    sb.append("  stop: ").append(stop).append("\n");
    sb.append("  journeyName: ").append(journeyName).append("\n");
    sb.append("  geometryRef: ").append(geometryRef).append("\n");
    sb.append("  color: ").append(color).append("\n");
    sb.append("  noNamespaceSchemaLocation: ").append(noNamespaceSchemaLocation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
