/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class JourneyType {
  
  @SerializedName("routeIdxTo")
  private Integer routeIdxTo = null;
  @SerializedName("routeIdxFrom")
  private Integer routeIdxFrom = null;
  @SerializedName("type")
  private String type = null;

  /**
   * End of validity on total route.
   **/
  @ApiModelProperty(required = true, value = "End of validity on total route.")
  public Integer getRouteIdxTo() {
    return routeIdxTo;
  }
  public void setRouteIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
  }

  /**
   * Start of validity on total route
   **/
  @ApiModelProperty(required = true, value = "Start of validity on total route")
  public Integer getRouteIdxFrom() {
    return routeIdxFrom;
  }
  public void setRouteIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
  }

  /**
   * The attribute type specifies the type of the journey. Valid values are VAS, LDT (Long Distance Train), REG (Regional train), BUS , BOAT, TRAM, TAXI (Taxi/Telebus)
   **/
  @ApiModelProperty(required = true, value = "The attribute type specifies the type of the journey. Valid values are VAS, LDT (Long Distance Train), REG (Regional train), BUS , BOAT, TRAM, TAXI (Taxi/Telebus)")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyType journeyType = (JourneyType) o;
    return (this.routeIdxTo == null ? journeyType.routeIdxTo == null : this.routeIdxTo.equals(journeyType.routeIdxTo)) &&
        (this.routeIdxFrom == null ? journeyType.routeIdxFrom == null : this.routeIdxFrom.equals(journeyType.routeIdxFrom)) &&
        (this.type == null ? journeyType.type == null : this.type.equals(journeyType.type));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.routeIdxTo == null ? 0: this.routeIdxTo.hashCode());
    result = 31 * result + (this.routeIdxFrom == null ? 0: this.routeIdxFrom.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyType {\n");
    
    sb.append("  routeIdxTo: ").append(routeIdxTo).append("\n");
    sb.append("  routeIdxFrom: ").append(routeIdxFrom).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
