/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class JourneyName {
  
  @SerializedName("routeIdxTo")
  private Integer routeIdxTo = null;
  @SerializedName("routeIdxFrom")
  private Integer routeIdxFrom = null;
  @SerializedName("name")
  private String name = null;

  /**
   * End of validity on total route.
   **/
  @ApiModelProperty(required = true, value = "End of validity on total route.")
  public Integer getRouteIdxTo() {
    return routeIdxTo;
  }
  public void setRouteIdxTo(Integer routeIdxTo) {
    this.routeIdxTo = routeIdxTo;
  }

  /**
   * Start of validity on total route
   **/
  @ApiModelProperty(required = true, value = "Start of validity on total route")
  public Integer getRouteIdxFrom() {
    return routeIdxFrom;
  }
  public void setRouteIdxFrom(Integer routeIdxFrom) {
    this.routeIdxFrom = routeIdxFrom;
  }

  /**
   * Name to be displayed
   **/
  @ApiModelProperty(required = true, value = "Name to be displayed")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JourneyName journeyName = (JourneyName) o;
    return (this.routeIdxTo == null ? journeyName.routeIdxTo == null : this.routeIdxTo.equals(journeyName.routeIdxTo)) &&
        (this.routeIdxFrom == null ? journeyName.routeIdxFrom == null : this.routeIdxFrom.equals(journeyName.routeIdxFrom)) &&
        (this.name == null ? journeyName.name == null : this.name.equals(journeyName.name));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.routeIdxTo == null ? 0: this.routeIdxTo.hashCode());
    result = 31 * result + (this.routeIdxFrom == null ? 0: this.routeIdxFrom.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class JourneyName {\n");
    
    sb.append("  routeIdxTo: ").append(routeIdxTo).append("\n");
    sb.append("  routeIdxFrom: ").append(routeIdxFrom).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
