/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.CoordLocation;
import io.swagger.client.model.StopLocation;
import java.util.*;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LocationList {
  
  @SerializedName("errorText")
  private String errorText = null;
  @SerializedName("error")
  private String error = null;
  @SerializedName("serverdate")
  private Date serverdate = null;
  @SerializedName("servertime")
  private String servertime = null;
  @SerializedName("StopLocation")
  private List<StopLocation> stopLocation = null;
  @SerializedName("CoordLocation")
  private List<CoordLocation> coordLocation = null;
  @SerializedName("noNamespaceSchemaLocation")
  private String noNamespaceSchemaLocation = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getErrorText() {
    return errorText;
  }
  public void setErrorText(String errorText) {
    this.errorText = errorText;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }
  public void setError(String error) {
    this.error = error;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getServerdate() {
    return serverdate;
  }
  public void setServerdate(Date serverdate) {
    this.serverdate = serverdate;
  }

  /**
   * Current server time in format HH:MM
   **/
  @ApiModelProperty(value = "Current server time in format HH:MM")
  public String getServertime() {
    return servertime;
  }
  public void setServertime(String servertime) {
    this.servertime = servertime;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<StopLocation> getStopLocation() {
    return stopLocation;
  }
  public void setStopLocation(List<StopLocation> stopLocation) {
    this.stopLocation = stopLocation;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<CoordLocation> getCoordLocation() {
    return coordLocation;
  }
  public void setCoordLocation(List<CoordLocation> coordLocation) {
    this.coordLocation = coordLocation;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getNoNamespaceSchemaLocation() {
    return noNamespaceSchemaLocation;
  }
  public void setNoNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationList locationList = (LocationList) o;
    return (this.errorText == null ? locationList.errorText == null : this.errorText.equals(locationList.errorText)) &&
        (this.error == null ? locationList.error == null : this.error.equals(locationList.error)) &&
        (this.serverdate == null ? locationList.serverdate == null : this.serverdate.equals(locationList.serverdate)) &&
        (this.servertime == null ? locationList.servertime == null : this.servertime.equals(locationList.servertime)) &&
        (this.stopLocation == null ? locationList.stopLocation == null : this.stopLocation.equals(locationList.stopLocation)) &&
        (this.coordLocation == null ? locationList.coordLocation == null : this.coordLocation.equals(locationList.coordLocation)) &&
        (this.noNamespaceSchemaLocation == null ? locationList.noNamespaceSchemaLocation == null : this.noNamespaceSchemaLocation.equals(locationList.noNamespaceSchemaLocation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.errorText == null ? 0: this.errorText.hashCode());
    result = 31 * result + (this.error == null ? 0: this.error.hashCode());
    result = 31 * result + (this.serverdate == null ? 0: this.serverdate.hashCode());
    result = 31 * result + (this.servertime == null ? 0: this.servertime.hashCode());
    result = 31 * result + (this.stopLocation == null ? 0: this.stopLocation.hashCode());
    result = 31 * result + (this.coordLocation == null ? 0: this.coordLocation.hashCode());
    result = 31 * result + (this.noNamespaceSchemaLocation == null ? 0: this.noNamespaceSchemaLocation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationList {\n");
    
    sb.append("  errorText: ").append(errorText).append("\n");
    sb.append("  error: ").append(error).append("\n");
    sb.append("  serverdate: ").append(serverdate).append("\n");
    sb.append("  servertime: ").append(servertime).append("\n");
    sb.append("  stopLocation: ").append(stopLocation).append("\n");
    sb.append("  coordLocation: ").append(coordLocation).append("\n");
    sb.append("  noNamespaceSchemaLocation: ").append(noNamespaceSchemaLocation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
