/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Note {
  
  @SerializedName("priority")
  private String priority = null;
  public enum SeverityEnum {
     high,  normal,  low, 
  };
  @SerializedName("severity")
  private SeverityEnum severity = null;
  @SerializedName("key")
  private String key = null;

  /**
   * Priority of the note which can be used to order the notes in the list.
   **/
  @ApiModelProperty(required = true, value = "Priority of the note which can be used to order the notes in the list.")
  public String getPriority() {
    return priority;
  }
  public void setPriority(String priority) {
    this.priority = priority;
  }

  /**
   * Severity of this note, can be high, normal or low
   **/
  @ApiModelProperty(required = true, value = "Severity of this note, can be high, normal or low")
  public SeverityEnum getSeverity() {
    return severity;
  }
  public void setSeverity(SeverityEnum severity) {
    this.severity = severity;
  }

  /**
   * Type of this note
   **/
  @ApiModelProperty(value = "Type of this note")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Note note = (Note) o;
    return (this.priority == null ? note.priority == null : this.priority.equals(note.priority)) &&
        (this.severity == null ? note.severity == null : this.severity.equals(note.severity)) &&
        (this.key == null ? note.key == null : this.key.equals(note.key));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.priority == null ? 0: this.priority.hashCode());
    result = 31 * result + (this.severity == null ? 0: this.severity.hashCode());
    result = 31 * result + (this.key == null ? 0: this.key.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Note {\n");
    
    sb.append("  priority: ").append(priority).append("\n");
    sb.append("  severity: ").append(severity).append("\n");
    sb.append("  key: ").append(key).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
