/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.Point;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Points {
  
  @SerializedName("Point")
  private List<Point> point = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Point> getPoint() {
    return point;
  }
  public void setPoint(List<Point> point) {
    this.point = point;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Points points = (Points) o;
    return (this.point == null ? points.point == null : this.point.equals(points.point));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.point == null ? 0: this.point.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Points {\n");
    
    sb.append("  point: ").append(point).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
