/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Point {
  
  @SerializedName("lon")
  private String lon = null;
  @SerializedName("lat")
  private String lat = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getLon() {
    return lon;
  }
  public void setLon(String lon) {
    this.lon = lon;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getLat() {
    return lat;
  }
  public void setLat(String lat) {
    this.lat = lat;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Point point = (Point) o;
    return (this.lon == null ? point.lon == null : this.lon.equals(point.lon)) &&
        (this.lat == null ? point.lat == null : this.lat.equals(point.lat));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.lon == null ? 0: this.lon.hashCode());
    result = 31 * result + (this.lat == null ? 0: this.lat.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Point {\n");
    
    sb.append("  lon: ").append(lon).append("\n");
    sb.append("  lat: ").append(lat).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
