/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.TimetableInfo;
import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SystemInfo {
  
  @SerializedName("TimetableInfo")
  private TimetableInfo timetableInfo = null;
  @SerializedName("errorText")
  private String errorText = null;
  @SerializedName("error")
  private String error = null;
  @SerializedName("serverdate")
  private Date serverdate = null;
  @SerializedName("servertime")
  private String servertime = null;
  @SerializedName("noNamespaceSchemaLocation")
  private String noNamespaceSchemaLocation = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public TimetableInfo getTimetableInfo() {
    return timetableInfo;
  }
  public void setTimetableInfo(TimetableInfo timetableInfo) {
    this.timetableInfo = timetableInfo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getErrorText() {
    return errorText;
  }
  public void setErrorText(String errorText) {
    this.errorText = errorText;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getError() {
    return error;
  }
  public void setError(String error) {
    this.error = error;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getServerdate() {
    return serverdate;
  }
  public void setServerdate(Date serverdate) {
    this.serverdate = serverdate;
  }

  /**
   * Current server time in format HH:MM
   **/
  @ApiModelProperty(value = "Current server time in format HH:MM")
  public String getServertime() {
    return servertime;
  }
  public void setServertime(String servertime) {
    this.servertime = servertime;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getNoNamespaceSchemaLocation() {
    return noNamespaceSchemaLocation;
  }
  public void setNoNamespaceSchemaLocation(String noNamespaceSchemaLocation) {
    this.noNamespaceSchemaLocation = noNamespaceSchemaLocation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SystemInfo systemInfo = (SystemInfo) o;
    return (this.timetableInfo == null ? systemInfo.timetableInfo == null : this.timetableInfo.equals(systemInfo.timetableInfo)) &&
        (this.errorText == null ? systemInfo.errorText == null : this.errorText.equals(systemInfo.errorText)) &&
        (this.error == null ? systemInfo.error == null : this.error.equals(systemInfo.error)) &&
        (this.serverdate == null ? systemInfo.serverdate == null : this.serverdate.equals(systemInfo.serverdate)) &&
        (this.servertime == null ? systemInfo.servertime == null : this.servertime.equals(systemInfo.servertime)) &&
        (this.noNamespaceSchemaLocation == null ? systemInfo.noNamespaceSchemaLocation == null : this.noNamespaceSchemaLocation.equals(systemInfo.noNamespaceSchemaLocation));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.timetableInfo == null ? 0: this.timetableInfo.hashCode());
    result = 31 * result + (this.errorText == null ? 0: this.errorText.hashCode());
    result = 31 * result + (this.error == null ? 0: this.error.hashCode());
    result = 31 * result + (this.serverdate == null ? 0: this.serverdate.hashCode());
    result = 31 * result + (this.servertime == null ? 0: this.servertime.hashCode());
    result = 31 * result + (this.noNamespaceSchemaLocation == null ? 0: this.noNamespaceSchemaLocation.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemInfo {\n");
    
    sb.append("  timetableInfo: ").append(timetableInfo).append("\n");
    sb.append("  errorText: ").append(errorText).append("\n");
    sb.append("  error: ").append(error).append("\n");
    sb.append("  serverdate: ").append(serverdate).append("\n");
    sb.append("  servertime: ").append(servertime).append("\n");
    sb.append("  noNamespaceSchemaLocation: ").append(noNamespaceSchemaLocation).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
