/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.TimeTableData;
import io.swagger.client.model.TimeTablePeriod;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TimetableInfo {
  
  @SerializedName("TimeTableData")
  private TimeTableData timeTableData = null;
  @SerializedName("TimeTablePeriod")
  private TimeTablePeriod timeTablePeriod = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public TimeTableData getTimeTableData() {
    return timeTableData;
  }
  public void setTimeTableData(TimeTableData timeTableData) {
    this.timeTableData = timeTableData;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public TimeTablePeriod getTimeTablePeriod() {
    return timeTablePeriod;
  }
  public void setTimeTablePeriod(TimeTablePeriod timeTablePeriod) {
    this.timeTablePeriod = timeTablePeriod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimetableInfo timetableInfo = (TimetableInfo) o;
    return (this.timeTableData == null ? timetableInfo.timeTableData == null : this.timeTableData.equals(timetableInfo.timeTableData)) &&
        (this.timeTablePeriod == null ? timetableInfo.timeTablePeriod == null : this.timeTablePeriod.equals(timetableInfo.timeTablePeriod));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.timeTableData == null ? 0: this.timeTableData.hashCode());
    result = 31 * result + (this.timeTablePeriod == null ? 0: this.timeTablePeriod.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimetableInfo {\n");
    
    sb.append("  timeTableData: ").append(timeTableData).append("\n");
    sb.append("  timeTablePeriod: ").append(timeTablePeriod).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
