/**
 * Reseplaneraren
 * Provides access to Västtrafik journey planner
 *
 * OpenAPI spec version: 1.10.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.DateBegin;
import io.swagger.client.model.DateEnd;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TimeTablePeriod {
  
  @SerializedName("DateBegin")
  private DateBegin dateBegin = null;
  @SerializedName("DateEnd")
  private DateEnd dateEnd = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public DateBegin getDateBegin() {
    return dateBegin;
  }
  public void setDateBegin(DateBegin dateBegin) {
    this.dateBegin = dateBegin;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public DateEnd getDateEnd() {
    return dateEnd;
  }
  public void setDateEnd(DateEnd dateEnd) {
    this.dateEnd = dateEnd;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeTablePeriod timeTablePeriod = (TimeTablePeriod) o;
    return (this.dateBegin == null ? timeTablePeriod.dateBegin == null : this.dateBegin.equals(timeTablePeriod.dateBegin)) &&
        (this.dateEnd == null ? timeTablePeriod.dateEnd == null : this.dateEnd.equals(timeTablePeriod.dateEnd));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.dateBegin == null ? 0: this.dateBegin.hashCode());
    result = 31 * result + (this.dateEnd == null ? 0: this.dateEnd.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeTablePeriod {\n");
    
    sb.append("  dateBegin: ").append(dateBegin).append("\n");
    sb.append("  dateEnd: ").append(dateEnd).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
